AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Document Types Services
  
Globals:
  Function:
    Timeout: 10

Parameters:
  DBStackName:
    Description: "DynamoDB database creation stack name"
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: dynamodb

Resources:
  GetAllDoctypesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./../src-ts/ 
      Handler:  adaptors/config/doctype-handlers.getDocTypeList
      Runtime: nodejs14.x
      MemorySize: 512
      Timeout: 100
      Layers:
        - !ImportValue docudata-nodejs-common-libs-CommonLibsLayer
        - !ImportValue docudata-baseplatform-applayer-BaseplatformApplicationLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue docudata-dynamodb:DocudataBasePlatformTable
      Events:
        GetAllItems:
          Type: HttpApi
          Properties:
            Path: /api/internal/config/doctype/v1
            Method: GET
  
  getDoctypeByIDFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./../src-ts/ 
      Handler: adaptors/config/doctype-handlers.getDocType
      Runtime: nodejs14.x
      MemorySize: 512
      Timeout: 100
      Layers:
        - !ImportValue docudata-nodejs-common-libs-CommonLibsLayer
        - !ImportValue docudata-baseplatform-applayer-BaseplatformApplicationLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue docudata-dynamodb:DocudataBasePlatformTable
      Events:
        GetAllItems:
          Type: HttpApi
          Properties:
            Path: /api/internal/config/doctype/v1/{id}
            Method: GET
  
  createDoctypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./../src-ts/ 
      Handler: adaptors/config/doctype-handlers.createDocType
      Runtime: nodejs14.x
      MemorySize: 512
      Timeout: 100
      Layers:
        - !ImportValue docudata-nodejs-common-libs-CommonLibsLayer
        - !ImportValue docudata-baseplatform-applayer-BaseplatformApplicationLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue docudata-dynamodb:DocudataBasePlatformTable
      Events:
        GetAllItems:
          Type: HttpApi
          Properties:
            Path: /api/internal/config/doctype/v1/create
            Method: POST
  
  updateDoctypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./../src-ts/ 
      Handler: adaptors/config/doctype-handlers.updateDocType
      Runtime: nodejs14.x
      MemorySize: 512
      Timeout: 100
      Layers:
        - !ImportValue docudata-nodejs-common-libs-CommonLibsLayer
        - !ImportValue docudata-baseplatform-applayer-BaseplatformApplicationLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue docudata-dynamodb:DocudataBasePlatformTable
      Events:
        GetAllItems:
          Type: HttpApi
          Properties:
            Path: /api/internal/config/doctype/v1/update/{id}
            Method: POST
   
Outputs:
  ApiEndpoint:
    Description: "Base URL for Document type related services"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/api/internal/config/doctype/v1"
  
  getAllDoctypes:
    Description: "GetAllDoctypesFunction ARN"
    Value: !GetAtt GetAllDoctypesFunction.Arn

  getDoctypeById:
    Description: "getDoctypeById Function ARN"
    Value: !GetAtt getDoctypeByIDFunction.Arn

  createDocType:
    Description: "createDocType Function ARN"
    Value: !GetAtt createDoctypeFunction.Arn

  updateDocType:
    Description: "updateDocType Function ARN"
    Value: !GetAtt updateDoctypeFunction.Arn
  