AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Groups Services 
  
Globals:
  Function:
    Timeout: 10

Parameters:
  DBStackName:
    Description: "DynamoDB database creation stack name"
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: dynamodb

Resources:
  GetAllGroups:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./../src-ts/ 
      Handler: adaptors/config/groups-handlers.getGroupsList
      Runtime: nodejs14.x
      MemorySize: 512
      Timeout: 100
      Layers:
        - !ImportValue docudata-nodejs-common-libs-CommonLibsLayer
        - !ImportValue docudata-baseplatform-applayer-BaseplatformApplicationLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue docudata-dynamodb:DocudataBasePlatformTable
      Events:
        GetAllItems:
          Type: HttpApi
          Properties:
            Path: /api/internal/config/group/v1
            Method: GET

  
  getGroupByIDFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./../src-ts/ 
      Handler: adaptors/config/groups-handlers.getGroup
      Runtime: nodejs14.x
      MemorySize: 512
      Timeout: 100
      Layers:
        - !ImportValue docudata-nodejs-common-libs-CommonLibsLayer
        - !ImportValue docudata-baseplatform-applayer-BaseplatformApplicationLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue docudata-dynamodb:DocudataBasePlatformTable
      Events:
        GetAllItems:
          Type: HttpApi
          Properties:
            Path: /api/internal/config/group/v1/{id}
            Method: GET
            CorsConfiguration:
              AllowOrigins:
                - "*"
              AllowHeaders:
                - "*"
              AllowMethods:
                - GET, POST,OPTIONS
              MaxAge: 600
  
  createGroupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./../src-ts/ 
      Handler: adaptors/config/groups-handlers.createGroup
      Runtime: nodejs14.x
      MemorySize: 512
      Timeout: 100
      Layers:
        - !ImportValue docudata-nodejs-common-libs-CommonLibsLayer
        - !ImportValue docudata-baseplatform-applayer-BaseplatformApplicationLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue docudata-dynamodb:DocudataBasePlatformTable
      Events:
        GetAllItems:
          Type: HttpApi
          Properties:
            Path: /api/internal/config/group/v1/create
            Method: POST

  
  updateGroupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./../src-ts/ 
      Handler: adaptors/config/groups-handlers.updateGroup
      Runtime: nodejs14.x
      MemorySize: 512
      Timeout: 100
      Layers:
        - !ImportValue docudata-nodejs-common-libs-CommonLibsLayer
        - !ImportValue docudata-baseplatform-applayer-BaseplatformApplicationLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue docudata-dynamodb:DocudataBasePlatformTable
      Events:
        GetAllItems:
          Type: HttpApi
          Properties:
            Path: /api/internal/config/group/v1/update/{id}
            Method: POST
          CorsConfiguration:
            AllowOrigins:
              - "*"
            AllowHeaders:
              - "*"
            AllowMethods:
              - GET, POST, OPTIONS
            MaxAge: 600
   
Outputs:
  ApiEndpoint:
    Description: "Base URL for All Groups related services"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/api/internal/config/group/v1"
  
  listGroups:
    Description: "GetAllGroups ARN"
    Value: !GetAtt GetAllGroups.Arn

  getGroupById:
    Description: "getGroupByID Function ARN"
    Value: !GetAtt getGroupByIDFunction.Arn

  createGroup:
    Description: "createGroup Function ARN"
    Value: !GetAtt createGroupFunction.Arn

  updateGroup:
    Description: "updateGroup Function ARN"
    Value: !GetAtt updateGroupFunction.Arn
  